sudo: required

services:
  - docker

env:
  matrix:
    - RUBY_VERSION=2.3
      env: PATH=$PATH:$PWD
    - RUBY_VERSION=2.2
      env: PATH=$PATH:$PWD
    - RUBY_VERSION=2.1.5
      env: PATH=$PATH:$PWD

install:
  - wget https://github.com/yunify/snips/releases/download/v0.3.6/snips-v0.3.6-linux_amd64.tar.gz -O /tmp/snips.tar.gz
  - tar -zxvf /tmp/snips.tar.gz
  - bundle install

before_script:
  - rake update
  - rake generate

script:
  - rake spec-runtime-ruby-${RUBY_VERSION}
