name: "Unit Test"

on: [push,pull_request]

jobs:
  unit_test:
    name: Unit Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        ruby: [ "2.5", "2.6", "2.7" ]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Bundle
        run: bundle install

      - name: Test
        run: bundle exec rake spec
